### ISSUE TITLE
Validate the TLD, matching it with real and accepted TLDs

### ISSUE THREAD

**Issue by rocboronat** [Fewlaps/quitnow-email-suggester#11]
Validating with a regex is great... but it's not reliable. It says that 'roc@fewlaps.con" is a valid e-mail :-1:

**Comment by EsteveAguilera** [comment]
Link to the "The Public Suffix List": 

https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat

**Comment by ed-george** [comment]
With the large amount of gTLD's being added each year, it seems highly unlikely that this is feasible as it would be difficult to maintain correctly.

**Comment by rocboronat** [comment]
Yes... but we can read the whole file @EsteveAguilera attatched, and update it when necessary. It seems simple to parse.

**Comment by ed-george** [comment]
Maybe using the list within a git submodule is the best option here

**Comment by rocboronat** [comment]
Having that file on a GitHub repo could be a great idea. I like it a lot!

By the way, as author of the idea, feel free to create it. We'll star it for sure, and hopefully use it as a submodule! :·)

**Comment by ed-george** [comment]
I have created a branch in my fork with this implemented but it will not build at present despite passing all tests in my IDE. I have not worked with a non-Android gradle based project before, so am not sure what I have done wrong. @rocboronat could you potentially email me to discuss this?

**Comment by rocboronat** [comment]
Of course! Here we go!

**Comment by rocboronat** [comment]
Hi @ed-george ! Just merged your development to our develop branch :·) THANK YOU!

Next step: validate the TLD using SuffixUtils.isValidSuffix()

**Comment by ed-george** [comment]
Glad I could help! Fingers crossed I will get a bit spare time to look into doing some more sometime

**Comment by rocboronat** [comment]
Released at 2.0.0

Thanks @ed-george for your work! :·)

**Comment by ed-george** [comment]
My pleasure - Will take a look at the code base again when I have some downtime
