### ISSUE TITLE
Hotmial to Hotmail

### ISSUE THREAD

**Issue by rocboronat** [Fewlaps/quitnow-email-suggester#22]

**Comment by ohrock** [comment]
No te olvides de "hotmale to hotmail"   ;-)

Happy?

**Comment by rocboronat** [comment]
Jjajajja valeee ahora la creo yo! xD

Roc Boronat
http://rocboron.at
http://fewlaps.com
... escrit des del mòbil, perdona'm la brevetat i les possibles faltes
ortogràfiques
