### ISSUE TITLE
False positives in Email Validator Tests

### ISSUE THREAD

**Issue by ed-george** [Fewlaps/quitnow-email-suggester#30]
I believe there are some tests that are defined in `EmailValidatorTest` that `assertFalse` when they should be true:

```
    //shouldSayKO7() 
    assertFalse(ev.isValidEmail(".email@example.com"));
    //shouldSayKO8() {
    assertFalse(ev.isValidEmail("email.@example.com"));
    //shouldSayKO9() {
    assertFalse(ev.isValidEmail("email..email@example.com"));
    //shouldSayKO14() {
    assertFalse(ev.isValidEmail("email@example..com"));
    //shouldSayKO15() {
    assertFalse(ev.isValidEmail("Abc..123@example.com"));
```

As per [RFC5322](http://tools.ietf.org/html/rfc5322) all of these addresses are _valid_, but just uncommonly used.

I am currently drafting a fix for #26 that may clean it up, but would like some feedback on this.

**Comment by rocboronat** [comment]
Great! Actually, I'm not sure where I found a long list of tests to do that test battery... but if you're sure that they should fail, it will be great to improve it. Thanks for the issue!

**Comment by ed-george** [comment]
I have changed the Email Pattern regex (see my fork's [development branch](https://github.com/ed-george/quitnow-email-suggester/commit/4938244bd523b0a5722a5255786822999a270642)) as it is more inclusive, follows the RFC specification more closely and passes the aforementioned tests.

**Comment by rocboronat** [comment]
Just found the blog post with that battery of test: http://codefool.tumblr.com/post/15288874550/list-of-valid-and-invalid-email-addresses

I didn't double checked it. Sorry about that!

Thanks for the work!!
