### ISSUE TITLE
Create .isAlias() tests

### ISSUE THREAD

**Issue by rocboronat** [Fewlaps/quitnow-email-suggester#33]

**Comment by ed-george** [comment]
I did add some basic tests in https://github.com/Fewlaps/quitnow-email-suggester/commit/cc49ec3e36c8bc2f534522d88f9efcdd94255f8b, not sure if there was anything I missed but can add more comprehensive ones if required.

**Comment by rocboronat** [comment]
Whop! I didn't seen them! :·) Closing!
